Class {
	#name : 'CRFTSBinderCleaner',
	#superclass : 'FASTTypeScriptVisitor',
	#category : 'Carrefour-TypeScript-FastAndBindingGenerator',
	#package : 'Carrefour-TypeScript-FastAndBindingGenerator'
}

{ #category : 'visiting' }
CRFTSBinderCleaner >> visitFASTTypeScriptFunctionDeclaration: aFASTTypeScriptFunctionDeclaration [
	aFASTTypeScriptFunctionDeclaration famix: nil.
	"^ super visitFASTTypeScriptFunctionDeclaration: aFASTTypeScriptFunctionDeclaration"
]
